- name:     set container alerts
  set_fact:
    _alert: "{{ lookup('template', 'alert-template.yml.j2', template_vars={'service_name': item.name }) | from_yaml }}"
  loop:     "{{ containers }}"
  loop_control:
    label: "{{ item.name }}"
  when: item.enabled and item.running
  register: _alerts
  tags:
    - podman-deploy
    - containers
    - alerts

- name: make a list of alerts
  vars:
    _alert_rules: "{{ _alerts.results | map(attribute='ansible_facts._alert') | list }}"
  set_fact:
    container_alerts:
      groups:
        - name: "ContainersRunning{{ alert_name_suffix | camel_case }}"
          rules: "{{ _alert_rules }}"
          concurrency: 4
  when: containers
  tags:
    - podman-deploy
    - containers
    - alerts

#- debug:
#    var: container_alerts
#  tags:
#    - podman-deploy
#    - containers
#    - alerts

- name: alerts to file
  copy:
    dest: "{{ alerts_dir }}/container-{{ alert_name_suffix }}-alerts.yml"
    content: "{{ container_alerts | to_nice_yaml }}"
  when: containers
  tags:
    - podman-deploy
    - containers
    - alerts
