---
- name:   Install podman
  hosts:  all
  become: yes
  tasks:
    - name: install curl
      package:
        name:
          - curl
          - dnsutils
        state: present
  roles:
    - role: podman
  vars:
    proxy_env:
      http_proxy:  '192.168.3.15:3142'
      https_proxy: '192.168.3.15:3142'
    registries:
      search:
        - 192.168.3.15:3128
#        - docker.io
      insecure:
        - 192.168.3.15:3128
        - docker.io
      block: [ ]

- name:   Setup podman-deploy
  hosts:  all
  become: yes
  roles:
    - role: podman-deploy
  vars:
    proxy_env:
      http_proxy:  '192.168.3.15:3128'
      https_proxy: '192.168.3.15:3128'
    containers:
      - name:    pihole
        image:   docker.io/pihole/pihole:latest
        network: podman
#        user:    999
#        group:   999
        enabled: yes
        running: yes
        exposes:
          - 127.0.0.1:8053:53/tcp
          - 127.0.0.1:8053:53/udp
          - 127.0.0.1:8091:80
          - 127.0.0.1:8092:443
        environment:
          - DNS1="1.1.1.1"
          - DNS2="8.8.8.8"
        mounts:
          - /etc/localtime:/etc/localtime:ro
          - /etc/timezone:/etc/timezone:ro
          - /opt/pihole/etc/pihole/:/etc/pihole/
          - /opt/pihole/etc/dnsmasq.d/:/etc/dnsmasq.d/
        manage_dirs:
          - /opt/pihole/etc/pihole/
          - /opt/pihole/etc/dnsmasq.d/
        manage_files:
          - path:    /opt/pihole/etc/pihole//custom.list
            content: |
                     10.0.0.1 test.local.lan
    pods:
      - name:    test-pod-piholes
        network: podman
        exposes:
          - 127.0.0.1:8054:53/tcp
          - 127.0.0.1:8054:53/udp
          - 127.0.0.1:8093:80
          - 127.0.0.1:8094:443
          - 127.0.0.1:8095:90
        containers:
          - name:    pihole-podded
            enabled: yes
            running: yes
            image:   docker.io/pihole/pihole:latest
            environment:
              - DNS1="1.1.1.1"
              - DNS2="8.8.8.8"
              - DNS3="8.8.8.4"
            mounts:
              - /etc/localtime:/etc/localtime:ro
              - /etc/timezone:/etc/timezone:ro
              - /opt/pihole2/etc/pihole/:/etc/pihole/
              - /opt/pihole2/etc/dnsmasq.d/:/etc/dnsmasq.d/
            manage_dirs:
              - /opt/pihole2/etc/pihole/
              - /opt/pihole2/etc/dnsmasq.d/
            manage_files:
              - path:    /opt/pihole2/etc/pihole/custom.list
                content: |
                         10.0.0.2 test.local.lan
          - name: test-httpd
            enabled: yes
            running: yes
            image: docker.io/httpd:2.4.39
            mounts:
              - /opt/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
            manage_dirs:
              - /opt/httpd/
            manage_files:
              - path: /opt/httpd/httpd.conf
                content: |
                         ServerRoot "/usr/local/apache2"
                         Listen 90
                         LoadModule mpm_event_module modules/mod_mpm_event.so
                         LoadModule authn_file_module modules/mod_authn_file.so
                         LoadModule authn_core_module modules/mod_authn_core.so
                         LoadModule authz_host_module modules/mod_authz_host.so
                         LoadModule authz_groupfile_module modules/mod_authz_groupfile.so
                         LoadModule authz_user_module modules/mod_authz_user.so
                         LoadModule authz_core_module modules/mod_authz_core.so
                         LoadModule access_compat_module modules/mod_access_compat.so
                         LoadModule auth_basic_module modules/mod_auth_basic.so
                         LoadModule reqtimeout_module modules/mod_reqtimeout.so
                         LoadModule filter_module modules/mod_filter.so
                         LoadModule mime_module modules/mod_mime.so
                         LoadModule log_config_module modules/mod_log_config.so
                         LoadModule env_module modules/mod_env.so
                         LoadModule headers_module modules/mod_headers.so
                         LoadModule setenvif_module modules/mod_setenvif.so
                         LoadModule version_module modules/mod_version.so
                         LoadModule unixd_module modules/mod_unixd.so
                         LoadModule status_module modules/mod_status.so
                         LoadModule autoindex_module modules/mod_autoindex.so
                         LoadModule dir_module modules/mod_dir.so
                         LoadModule alias_module modules/mod_alias.so
                         <IfModule unixd_module>
                         User daemon
                         Group daemon
                         </IfModule>
                         ServerAdmin you@example.com
                         <Directory />
                             AllowOverride none
                             Require all denied
                         </Directory>
                         DocumentRoot "/usr/local/apache2/htdocs"
                         <Directory "/usr/local/apache2/htdocs">
                             Options Indexes FollowSymLinks
                             AllowOverride None
                             Require all granted
                         </Directory>
                         <IfModule dir_module>
                             DirectoryIndex index.html
                         </IfModule>
                         <Files ".ht*">
                             Require all denied
                         </Files>
                         ErrorLog /proc/self/fd/2
                         LogLevel warn
                         <IfModule log_config_module>
                             LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
                             LogFormat "%h %l %u %t \"%r\" %>s %b" common
                             <IfModule logio_module>
                               LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\" %I %O" combinedio
                             </IfModule>
                             CustomLog /proc/self/fd/1 common
                         </IfModule>
                         <IfModule alias_module>
                             ScriptAlias /cgi-bin/ "/usr/local/apache2/cgi-bin/"
                         </IfModule>
                         <Directory "/usr/local/apache2/cgi-bin">
                             AllowOverride None
                             Options None
                             Require all granted
                         </Directory>
                         <IfModule headers_module>
                             RequestHeader unset Proxy early
                         </IfModule>
                         <IfModule mime_module>
                             TypesConfig conf/mime.types
                             AddType application/x-compress .Z
                             AddType application/x-gzip .gz .tgz
                         </IfModule>